receivers:
  nop:


processors:
  nop:

exporters:
  coralogix:
    # endpoint: "http://localhost:8000"
    endpoint: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    private_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    application_name: "APP_NAME"
    # Deprecated: [v0.47.0] SubSystem will remove in the next version
    subsystem_name: "SUBSYSTEM_NAME"
    timeout: 5s


service:
  pipelines:
    traces:
      receivers: [nop]
      processors: [nop]
      exporters: [coralogix]
