receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch:
    send_batch_size: 50
    timeout: 5s
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    # Will encode the whole OTEL message in json
    # This format happen after extracting labels
    format: json
    labels:
      attributes:
        container_name: ""
        source: ""
      resource:
        host.name: "hostname"

extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 64

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [ fluentforward ]
      processors: [ memory_limiter, batch ]
      exporters: [ loki ]
